security:
    acl:
        connection: default

    encoders:
        Impetus\AppBundle\Entity\User:
            algorithm: sha256
            encode-as-base64: true
            iterations: 10

    providers:
        main:
            entity: { class: Impetus\AppBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login: ~
            logout: ~
            security: true
            anonymous: true

    role_hierarchy:
        ROLE_TA: ROLE_STUDENT, ROLE_PARENT
        ROLE_MENTOR: ROLE_STUDENT, ROLE_PARENT
        ROLE_TEACHER: [ROLE_TA, ROLE_MENTOR]
        ROLE_ADMIN: [ROLE_TA, ROLE_MENTOR, ROLE_TEACHER]

    access_control:
#        - { path: ^/user/new, roles: [ROLE_TA, ROLE_MENTOR] }
#        - { path: ^/attendance, roles: ROLE_STUDENT }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
