_home:
    pattern: /
    defaults: { _controller: ImpetusAppBundle:Home:get }

_attendance:
    pattern: /attendance
    defaults: { _controller: ImpetusAppBundle:Attendance:get }

_district_edit:
    pattern: /district/{id}/edit
    defaults: { _controller: ImpetusAppBundle:District:edit }
    requirements:
        id: \d+

_district_list:
    pattern: /district
    defaults: { _controller: ImpetusAppBundle:District:list }

_district_new:
    pattern: /district/new
    defaults: { _controller: ImpetusAppBundle:District:new }

_district_update_grade:
    pattern: /district/user/{userId}/grade
    defaults: { _controller: ImpetusAppBundle:District:updateGrade }
    options:
        expose: true
    requirements:
        userId: \d+
        _method: POST

_login:
    pattern: /login
    defaults: { _controller: ImpetusAppBundle:Login:login }

_login_check:
    pattern: /login_check

_logout:
    pattern: /logout

_path:
    pattern: /path
    defaults: { _controller: ImpetusAppBundle:Path:get }

_path_nodes:
    pattern: /path_nodes
    defaults: { _controller: ImpetusAppBundle:Path:nodes, _format: json }
    options:
        expose: true

_path_show:
    pattern: /path/{id}
    defaults: { _controller: ImpetusAppBundle:Path:show }
    options:
        expose: true
    requirements:
        id: \d+

_schedule:
    pattern: /schedule
    defaults: { _controller: ImpetusAppBundle:Schedule:get }

_survey:
    pattern: /survey
    defaults: { _controller: ImpetusAppBundle:Survey:get }

_quiz:
    pattern: /quiz
    defaults: { _controller: ImpetusAppBundle:Quiz:list }

_quiz_show:
    pattern: /quiz/{id}
    defaults: { _controller: ImpetusAppBundle:Quiz:show }
    requirements:
        id: \d+

_quiz_new:
    pattern: /quiz/new
    defaults: { _controller: ImpetusAppBundle:Quiz:new }

_user_edit:
    pattern: /user/{id}/edit
    defaults: { _controller: ImpetusAppBundle:User:edit }
    requirements:
        id: \d+

_user_list:
    pattern: /user
    defaults: { _controller: ImpetusAppBundle:User:list }

_user_new:
    pattern: /user/new
    defaults: { _controller: ImpetusAppBundle:User:new }

_user_search:
    pattern: /user/{type}/search
    defaults: { _controller: ImpetusAppBundle:User:search }
    options:
        expose: true

_user_show:
    pattern: /user/{id}
    defaults: { _controller: ImpetusAppBundle:User:show }
    requirements:
        id: \d+
