_home:
    pattern: /
    defaults: { _controller: ImpetusAppBundle:Home:get }

_attendance:
    pattern: /attendance
    defaults: { _controller: ImpetusAppBundle:Attendance:get }

_login:
    pattern: /login
    defaults: { _controller: ImpetusAppBundle:Login:login }

_login_check:
    pattern: /login_check

_logout:
    pattern: /logout

_path:
    pattern: /path
    defaults: { _controller: ImpetusAppBundle:Path:get }

_register:
    pattern: /register
    defaults: { _controller: ImpetusAppBundle:Register:get }
    requirements:
        _method: GET

_register_process:
    pattern: /register
    defaults: { _controller: ImpetusAppBundle:Register:post }
    requirements:
        _method: POST

_schedule:
    pattern: /schedule
    defaults: { _controller: ImpetusAppBundle:Schedule:get }

_survey:
    pattern: /survey
    defaults: { _controller: ImpetusAppBundle:Survey:get }

_quiz:
    pattern: /quiz
    defaults: { _controller: ImpetusAppBundle:Quiz:list }

_quiz_show:
    pattern: /quiz/{id}
    defaults: { _controller: ImpetusAppBundle:Quiz:show }
    requirements:
        id: \d+

_quiz_new:
    pattern: /quiz/new
    defaults: { _controller: ImpetusAppBundle:Quiz:new }