_home:
    pattern: /
    defaults: { _controller: ImpetusAppBundle:Home:get }

_attendance:
    pattern: /attendance
    defaults: { _controller: ImpetusAppBundle:Attendance:get }

_analytics:
    resource: "@ImpetusAppBundle/Controller/AnalyticsController.php"
    type:     annotation

_district:
    resource: "@ImpetusAppBundle/Controller/DistrictController.php"
    type:     annotation

_login:
    pattern: /login
    defaults: { _controller: ImpetusAppBundle:Login:login }

_login_check:
    pattern: /login_check

_logout:
    pattern: /logout

_message:
    resource: "@ImpetusAppBundle/Controller/MessageController.php"
    type:     annotation

_path:
    resource: "@ImpetusAppBundle/Controller/PathController.php"
    type:     annotation

_schedule:
    pattern: /schedule
    defaults: { _controller: ImpetusAppBundle:Schedule:get }

_survey:
    pattern: /survey
    defaults: { _controller: ImpetusAppBundle:Survey:get }

_quiz:
    resource: "@ImpetusAppBundle/Controller/QuizController.php"
    type:     annotation

_user:
    resource: "@ImpetusAppBundle/Controller/UserController.php"
    type:     annotation

_year:
    resource: "@ImpetusAppBundle/Controller/YearController.php"
    type:     annotation