parameters:
    analytics_base: Impetus\AppBundle\Analytics
    service_base:   Impetus\AppBundle\Service

services:
    impetus_app.event.initial_academic_year_setter:
        class: Impetus\AppBundle\EventListener\ImpetusControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    analytics_service:
        class:     %service_base%\AnalyticsService
        arguments: [ @doctrine ]

    csv_service:
        class: %service_base%\CsvService

    message_service:
        class:     %service_base%\MessageService
        arguments: [ @doctrine, @mailer ]

    year_service:
        class:     %service_base%\YearService
        arguments: [ @doctrine, @session ]


    abstract_result:
        class:    %analytics_base%\AbstractResult
        abstract: true
        calls:
            - [ setCsvService, [ @csv_service ] ]
            - [ setTemplatingService, [ @templating ] ]

    complex_result:
        class:  %analytics_base%\ComplexResult
        parent: abstract_result

    simple_result:
        class:  %analytics_base%\SimpleResult
        parent: abstract_result

    students_served_result:
        class:  %analytics_base%\StudentsServedResult
        parent: abstract_result


#    impetus_app.example:
#        class: %impetus_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
